import Head from "next/head";
import Hero from "../../components/Hero";
import { Spline_Sans } from "next/font/google";

const splineSans = Spline_Sans({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Harshvardhan Agarwal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-708 mx-auto">
        <div className={splineSans.className}>
          <Hero />
        </div>
      </div>
    </>
  );
}
